framework:
    secret: '%env(APP_SECRET)%'

    php_errors:
        log: true

    validation:
        enabled: true
        cache: 'validator.mapping.cache.doctrine.apc'
        mapping:
            paths:
                - 'src/Resources/config/validation'

    translator:
        enabled: false
