---
language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files
env:
  - SYMFONY_VERSION="4.0.*" DB=sqlite
install:
  - cp .env.dist .env
  - composer install
script:
  - bin/console app:data:import
