App\Entity\Comment:
    properties:
        text:
            - Type: string
            - NotBlank:
                message: 'The comment cannot be empty.'
            - Length:
                min: 10
                max: 1024
                minMessage: 'The comment must be at least {{ limit }} characters long.'
                maxMessage: 'The comment cannot be longer than {{ limit }} characters.'
